## Assignment Week 6

1.   Link to cutsomer Data Set : [Click Here to access the Dataset](https://drive.google.com/file/d/1udUjxrM5LSXpdnzhS1uX8KGf-AlGd3xc/view?usp=sharing)
2.   List item

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

In [2]:
customer_data = pd.read_csv('/content/sample_data/customer_dataset.csv')

In [3]:
# Viewing the some information in the Dataset
customer_data.head()

,Age,Income,Gender,City,Education,MaritalStatus,LoyaltyScore,Purchased
0,63.0,NaN,Female,Ibadan,Diploma,Single,91.0,Yes
1,20.0,50287.0,Male,Abuja,High School,Divorced,30.4,Yes
2,46.0,142225.0,Male,Port Harcourt,Bachelor,NaN,4.0,No
3,52.0,88456.0,Female,Abuja,High School,Single,52.2,Yes
4,56.0,160792.0,Male,Ibadan,Bachelor,NaN,64.7,Yes

### Data Exploration

In [4]:
# Getting information abot the dataset
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            1080 non-null   float64
 1   Income         1080 non-null   float64
 2   Gender         1080 non-null   object
 3   City           1080 non-null   object
 4   Education      1080 non-null   object
 5   MaritalStatus  1080 non-null   object
 6   LoyaltyScore   1080 non-null   float64
 7   Purchased      1080 non-null   object
dtypes: float64(3), object(5)
memory usage: 75.1+ KB

In [5]:
# Checking form missing Data
customer_data.isnull().sum()

Age              120
Income           120
Gender           120
City             120
Education        120
MaritalStatus    120
LoyaltyScore     120
Purchased        120
dtype: int64

In [6]:
# percentage of missing Data
customer_data.isnull().sum() / len(customer_data) * 100

Age              10.0
Income           10.0
Gender           10.0
City             10.0
Education        10.0
MaritalStatus    10.0
LoyaltyScore     10.0
Purchased        10.0
dtype: float64

In [7]:
customer_data.describe()

               Age         Income  LoyaltyScore
count  1080.000000    1080.000000   1080.000000
mean     43.981481   98813.677778     50.617130
std      14.907488   46179.052087     27.853663
min      18.000000   20078.000000      1.000000
25%      32.000000   59210.750000     25.700000
50%      44.000000   99473.500000     52.050000
75%      57.000000  138722.500000     74.100000
max      69.000000  179869.000000     99.700000

### Handling Missing Values

In [8]:
# Filling age with missing values
customer_data['Age']= customer_data['Age'].fillna(customer_data['Age'].median())

In [9]:
customer_data.head(20)

,Age,Income,Gender,City,Education,MaritalStatus,LoyaltyScore,Purchased
0,63.0,NaN,Female,Ibadan,Diploma,Single,91.0,Yes
1,20.0,50287.0,Male,Abuja,High School,Divorced,30.4,Yes
2,46.0,142225.0,Male,Port Harcourt,Bachelor,NaN,4.0,No
3,52.0,88456.0,Female,Abuja,High School,Single,52.2,Yes
4,56.0,160792.0,Male,Ibadan,Bachelor,NaN,64.7,Yes
5,44.0,87573.0,Male,Ibadan,High School,Divorced,47.3,Yes
6,37.0,99067.0,Male,Benin,Diploma,Widowed,97.9,NaN
7,60.0,41980.0,Male,Benin,PhD,Divorced,69.8,No
8,40.0,95369.0,Female,Lagos,Master,Divorced,59.5,Yes
9,44.0,137053.0,Male,Enugu,Bachelor,Married,77.8,Yes
10,50.0,155073.0,Male,Lagos,PhD,Widowed,53.5,Yes
11,67.0,27780.0,Female,Abuja,Master,Single,87.3,Yes
12,44.0,99611.0,Female,Enugu,Bachelor,Divorced,47.1,No
13,27.0,123364.0,Female,Enugu,Master,Divorced,11.3,NaN
14,50.0,64122.0,Female,Lagos,Bachelor,Widowed,20.6,Yes
15,64.0,27460.0,Female,Enugu,Master,Married,45.2,Yes
16,50.0,145982.0,Female,Enugu,High School,Married,44.6,No
17,65.0,95359.0,Male,Benin,Master,Divorced,92.7,No
18,44.0,156106.0,Female,Lagos,Diploma,Widowed,43.7,NaN
19,37.0,NaN,Female,Enugu,High School,Married,9.1,No

In [10]:
#fill common missing values in column with the mode

def fill_missing_values(df,column_name):
  df[column_name]= df[column_name].fillna(df[column_name].mode()[0])
  return

column_to_fill = ['Gender','City','Education', 'MaritalStatus', 'Purchased']
for column in column_to_fill:
  fill_missing_values(customer_data,column)

In [11]:

customer_data.head(20)

,Age,Income,Gender,City,Education,MaritalStatus,LoyaltyScore,Purchased
0,63.0,NaN,Female,Ibadan,Diploma,Single,91.0,Yes
1,20.0,50287.0,Male,Abuja,High School,Divorced,30.4,Yes
2,46.0,142225.0,Male,Port Harcourt,Bachelor,Divorced,4.0,No
3,52.0,88456.0,Female,Abuja,High School,Single,52.2,Yes
4,56.0,160792.0,Male,Ibadan,Bachelor,Divorced,64.7,Yes
5,44.0,87573.0,Male,Ibadan,High School,Divorced,47.3,Yes
6,37.0,99067.0,Male,Benin,Diploma,Widowed,97.9,No
7,60.0,41980.0,Male,Benin,PhD,Divorced,69.8,No
8,40.0,95369.0,Female,Lagos,Master,Divorced,59.5,Yes
9,44.0,137053.0,Male,Enugu,Bachelor,Married,77.8,Yes
10,50.0,155073.0,Male,Lagos,PhD,Widowed,53.5,Yes
11,67.0,27780.0,Female,Abuja,Master,Single,87.3,Yes
12,44.0,99611.0,Female,Enugu,Bachelor,Divorced,47.1,No
13,27.0,123364.0,Female,Enugu,Master,Divorced,11.3,No
14,50.0,64122.0,Female,Lagos,Bachelor,Widowed,20.6,Yes
15,64.0,27460.0,Female,Enugu,Master,Married,45.2,Yes
16,50.0,145982.0,Female,Enugu,High School,Married,44.6,No
17,65.0,95359.0,Male,Benin,Master,Divorced,92.7,No
18,44.0,156106.0,Female,Lagos,Diploma,Widowed,43.7,No
19,37.0,NaN,Female,Enugu,High School,Married,9.1,No

In [12]:
customer_data['City'].unique()

array(['Ibadan', 'Abuja', 'Port Harcourt', 'Benin', 'Lagos', 'Enugu'],
      dtype=object)

### Dropping rows NAN rows in Income and Loyalty score

In [13]:
customer_data = customer_data.dropna(subset=['Income','LoyaltyScore'])

In [14]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 966 entries, 1 to 1198
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            966 non-null    float64
 1   Income         966 non-null    float64
 2   Gender         966 non-null    object
 3   City           966 non-null    object
 4   Education      966 non-null    object
 5   MaritalStatus  966 non-null    object
 6   LoyaltyScore   966 non-null    float64
 7   Purchased      966 non-null    object
dtypes: float64(3), object(5)
memory usage: 67.9+ KB

In [15]:
# convert the age and Income column to integer  except their are babies, in this case babies do not buy s=product for themselves

column_to_convert = ['Age','Income']
for column in column_to_convert:
  customer_data[column] = customer_data[column].astype(int)

# Encode Categorical Data

In [16]:
# creating the object of the encoder
le = LabelEncoder()

In [17]:
# calling the encoder
column_to_encode = ['Gender','Purchased']
for column in column_to_encode:
  customer_data[column] = le.fit_transform(customer_data[column])

In [18]:
customer_data.head()

,Age,Income,Gender,City,Education,MaritalStatus,LoyaltyScore,Purchased
1,20,50287,1,Abuja,High School,Divorced,30.4,1
2,46,142225,1,Port Harcourt,Bachelor,Divorced,4.0,0
3,52,88456,0,Abuja,High School,Single,52.2,1
4,56,160792,1,Ibadan,Bachelor,Divorced,64.7,1
5,44,87573,1,Ibadan,High School,Divorced,47.3,1

In [19]:
customer_data['MaritalStatus'].unique()

array(['Divorced', 'Single', 'Widowed', 'Married'], dtype=object)

### using oneHot Encoder for multiple columns

In [20]:
columns_to_transform = ['City','Education','MaritalStatus']
column_transformer = ColumnTransformer(transformers=[('encoder',OneHotEncoder(handle_unknown='ignore'),columns_to_transform)],remainder='passthrough')

In [21]:
encoded_array = column_transformer.fit_transform(customer_data)

In [22]:
customer_data = pd.DataFrame(
    encoded_array,
    columns=column_transformer.get_feature_names_out()
)
display(customer_data.head())

,encoder__City_Abuja,encoder__City_Benin,encoder__City_Enugu,encoder__City_Ibadan,encoder__City_Lagos,encoder__City_Port Harcourt,encoder__Education_Bachelor,encoder__Education_Diploma,encoder__Education_High School,encoder__Education_Master,encoder__Education_PhD,encoder__MaritalStatus_Divorced,encoder__MaritalStatus_Married,encoder__MaritalStatus_Single,encoder__MaritalStatus_Widowed,remainder__Age,remainder__Income,remainder__Gender,remainder__LoyaltyScore,remainder__Purchased
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,20.0,50287.0,1.0,30.4,1.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,46.0,142225.0,1.0,4.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,52.0,88456.0,0.0,52.2,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,56.0,160792.0,1.0,64.7,1.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,44.0,87573.0,1.0,47.3,1.0

## Scaling numerical Variable

In [23]:
# Scaling the salary and the numerical colum
column_to_scale = ['Age','Income']
scaler = StandardScaler()

In [28]:

column_to_scale = ['remainder__Age','remainder__Income']
customer_data[column_to_scale] = scaler.fit_transform(customer_data[column_to_scale])

print(customer_data)
customer_data.head()

     encoder__City_Abuja  encoder__City_Benin  encoder__City_Enugu  \
0                    1.0                  0.0                  0.0
1                    0.0                  0.0                  0.0
2                    1.0                  0.0                  0.0
3                    0.0                  0.0                  0.0
4                    0.0                  0.0                  0.0
..                   ...                  ...                  ...
961                  0.0                  0.0                  1.0
962                  0.0                  0.0                  0.0
963                  0.0                  0.0                  0.0
964                  1.0                  0.0                  0.0
965                  0.0                  0.0                  0.0

     encoder__City_Ibadan  encoder__City_Lagos  encoder__City_Port Harcourt  \
0                     0.0                  0.0                          0.0
1                     0.0                  0.0                          1.0
2                     0.0                  0.0                          0.0
3                     1.0                  0.0                          0.0
4                     1.0                  0.0                          0.0
..                    ...                  ...                          ...
961                   0.0                  0.0                          0.0
962                   0.0                  1.0                          0.0
963                   1.0                  0.0                          0.0
964                   0.0                  0.0                          0.0
965                   0.0                  1.0                          0.0

     encoder__Education_Bachelor  encoder__Education_Diploma  \
0                            0.0                         0.0
1                            1.0                         0.0
2                            0.0                         0.0
3                            1.0                         0.0
4                            0.0                         0.0
..                           ...                         ...
961                          0.0                         0.0
962                          1.0                         0.0
963                          0.0                         1.0
964                          0.0                         1.0
965                          0.0                         0.0

     encoder__Education_High School  encoder__Education_Master  \
0                               1.0                        0.0
1                               0.0                        0.0
2                               1.0                        0.0
3                               0.0                        0.0
4                               1.0                        0.0
..                              ...                        ...
961                             0.0                        1.0
962                             0.0                        0.0
963                             0.0                        0.0
964                             0.0                        0.0
965                             1.0                        0.0

     encoder__Education_PhD  encoder__MaritalStatus_Divorced  \
0                       0.0                              1.0
1                       0.0                              1.0
2                       0.0                              0.0
3                       0.0                              1.0
4                       0.0                              1.0
..                      ...                              ...
961                     0.0                              0.0
962                     0.0                              0.0
963                     0.0                              0.0
964                     0.0                              1.0
965                     0.0                              0.0

     encoder__MaritalStatus_Married  encoder__MaritalStatus_Single  \
0                               0.0                            0.0
1                               0.0                            0.0
2                               0.0                            1.0
3                               0.0                            0.0
4                               0.0                            0.0
..                              ...                            ...
961                             0.0                            0.0
962                             0.0                            0.0
963                             1.0                            0.0
964                             0.0                            0.0
965                             0.0                            1.0

     encoder__MaritalStatus_Widowed  remainder__Age  remainder__Income  \
0                               0.0       -1.693750          -1.036641
1                               0.0        0.142968           0.941399
2                               0.0        0.566826          -0.215438
3                               0.0        0.849398           1.340867
4                               0.0        0.001682          -0.234435
..                              ...             ...                ...
961                             1.0       -0.704748          -1.187848
962                             1.0       -1.835036           0.875069
963                             0.0       -0.139604          -0.503135
964                             0.0        0.778755          -1.063879
965                             0.0        0.354897          -1.237010

     remainder__Gender  remainder__LoyaltyScore  remainder__Purchased
0                  1.0                     30.4                   1.0
1                  1.0                      4.0                   0.0
2                  0.0                     52.2                   1.0
3                  1.0                     64.7                   1.0
4                  1.0                     47.3                   1.0
..                 ...                      ...                   ...
961                0.0                     58.3                   1.0
962                1.0                     80.7                   1.0
963                1.0                     85.7                   0.0
964                0.0                     15.7                   0.0
965                0.0                     51.7                   0.0

[966 rows x 20 columns]

,encoder__City_Abuja,encoder__City_Benin,encoder__City_Enugu,encoder__City_Ibadan,encoder__City_Lagos,encoder__City_Port Harcourt,encoder__Education_Bachelor,encoder__Education_Diploma,encoder__Education_High School,encoder__Education_Master,encoder__Education_PhD,encoder__MaritalStatus_Divorced,encoder__MaritalStatus_Married,encoder__MaritalStatus_Single,encoder__MaritalStatus_Widowed,remainder__Age,remainder__Income,remainder__Gender,remainder__LoyaltyScore,remainder__Purchased
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.693750,-1.036641,1.0,30.4,1.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.142968,0.941399,1.0,4.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.566826,-0.215438,0.0,52.2,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.849398,1.340867,1.0,64.7,1.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.001682,-0.234435,1.0,47.3,1.0

In [27]:
customer_data.head()

,encoder__City_Abuja,encoder__City_Benin,encoder__City_Enugu,encoder__City_Ibadan,encoder__City_Lagos,encoder__City_Port Harcourt,encoder__Education_Bachelor,encoder__Education_Diploma,encoder__Education_High School,encoder__Education_Master,encoder__Education_PhD,encoder__MaritalStatus_Divorced,encoder__MaritalStatus_Married,encoder__MaritalStatus_Single,encoder__MaritalStatus_Widowed,remainder__Age,remainder__Income,remainder__Gender,remainder__LoyaltyScore,remainder__Purchased
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.693750,-1.036641,1.0,30.4,1.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.142968,0.941399,1.0,4.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.566826,-0.215438,0.0,52.2,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.849398,1.340867,1.0,64.7,1.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.001682,-0.234435,1.0,47.3,1.0

### My reason


1.  I had to scale Age and Income so that one feature does not unfairly dominate the model simply because it has larger numbers.
2.   This is done to avoid the data from being bias and unfair when predicting.
3.   This is done also to the model to avoid noise.